# The URL the site will be built for
base_url = "https://vivek.ink"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
title = "â›“ Vivek"
description = "Hey you, welcome to my corner of the internet, I'm a sucker for computer softwares and minimilist design. I do programming prostitution to pay my bills." 

# description = "Hey you, welcome to my corner of the internet, we've been blind folded by this modern world and their sophisticated, crappy web design standards when infact the true design lies in the most simple sites.

theme = "archie-zola"
generate_feed = true
taxonomies = [
    {name = "tags", feed = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"
extra_syntaxes_and_themes = ["syntaxes", "syntaxes/move.sublime-syntax"]



[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
author = "Vivek"
# after_dark_menu = [
#     {url = "$BASE_URL", name = "Home"},
#     {url = "$BASE_URL/categories", name = "Categories"},
#     {url = "$BASE_URL/tags", name = "Tags"},
# ]
# after_dark_title = "ğŸŒˆ I am Vivek"
# control dark mode: auto | dark | toggle
mode = "dark"

# interal CDN resource
useCDN = false

favicon = "/icon/favicon.png"

copyright = "Vivek"

# ga = "G-6YGDB8SLBT"
ga = "G-ZDRZLL4SE0"

[extra.translations]
languages = [{name = "en", url = "/"}]

[[extra.translations.en]]
show_more = "Read more âŸ¶"
previous_page = "â† Previous"
next_page = "Next â†’"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "ğŸ Home", url = "/", weight = 2 },
    # { name = "All posts", url = "/posts", weight = 2 },
    { name = "âœï¸Microblog", url = "/microblog", weight = 2 },
    { name = "ğŸ–ï¸Nomading", url = "/nomading", weight = 2 },
    { name = "ğŸ“Lists", url = "/lists", weight = 2 },
    { name = "ğŸ•µï¸About", url = "/about", weight = 3 },
    { name = "ğŸ·ï¸Tags", url = "/tags", weight = 4 },
    { name = "ğŸŒ†Collage", url = "/collage", weight = 2 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/vivekascoder/"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/0xStateMachine/"

[[extra.social]]
icon = "youtube"
name = "Youtube"
url = "https://www.youtube.com/@vivekascoder"
